# Generated by Django 5.0 on 2024-08-20 11:07

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_otp_options_remove_profile_sem_profile_gender_and_more'),
        ('ticket', '0003_alter_events_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passes',
            name='technical1',
        ),
        migrations.RemoveField(
            model_name='passes',
            name='technical2',
        ),
        migrations.AddField(
            model_name='passes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='passes',
            name='day1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passes',
            name='day2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passes',
            name='day3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passes',
            name='psid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='passes',
            name='technical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Technical_Event', to='ticket.events'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 11, 7, 0, 49854, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 11, 17, 0, 50030, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rollno',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='_pass',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.passes'),
        ),
    ]
