# Generated by Django 5.0 on 2024-08-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RenameField(
            model_name='customticket',
            old_name='comment',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='customticket',
            old_name='is_paid',
            new_name='used',
        ),
        migrations.RemoveField(
            model_name='customticket',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customticket',
            name='user',
        ),
        migrations.AddField(
            model_name='customticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customticket',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customticket',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customticket',
            name='phone_no',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
